config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users

  root "pages#home"

  devise_scope :user do
    get "users",to: "devise/sessions#new"
  end
  # Defines the root path route ("/")
  # root "articles#index"
  get "user/:id", to: "users#show" , as: "user"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit {broadcast_append_to room}
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> {where(is_private: false)}
  after_create_commit { broadcast_append_to 'rooms' }
  has_many :messages
  after_initialize do
  if self.new_record?
    self.is_private = false
  end
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  scope :all_except, -> (user) {where.not(id:user)}
  after_create_commit { broadcast_append_to 'users' }
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def create
    @message = current_user.messages.create(body:msg_params[:body], room_id: params[:room_id])
  end

  private
  def msg_params
    params.require(:message).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user)
  end

  def show
    @single_room = Room.find(params[:id])
    @room = Room.new
    @rooms = Room.public_rooms
    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)
    @users = User.all_except(current_user)
    render 'index'
  end

  def create
    @room = Room.create(name: params["room"]["name"])
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Turbochat</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room, @message], remote: true, class:'d-flex') do |f| %>
    <%= f.text_field :body, id: 'chat-text', class: 'form-control msg-content', autocomplete: 'off' %>
    <%= f.submit data: {disable_with: false}, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class:'d-flex') do |f| %>
  <%= f.text_field :name, class: 'form-control', autocomplete: 'off' %>
  <%= f.submit data: {disable_with: false} %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Turbochat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
     <%= ".msg-#{current_user&.id}" %> {
     background-color: #007bff !important;
     padding: 10px;
     }
     <%= ".cont-#{current_user&.id}" %> {
     display: flex;
       justify-content: flex-end
     }
   </style>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <%= yield %>

  </body>
</html>

app/views/messages/_message.html.erb
<div class="cont-<%=message.user.id%>">
  <div class="message-box msg-<%= message.user.id %>">
    <% unless message.room.is_private %>
      <h6 class="name"> <%= message.user.email %> </h6>
    <% end %>
    <%= message.body %>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Tubochat</h1>
<p>Find me in app/views/pages/home.html.erb</p>

  <% if current_user %>

    <%= button_to "Log out", destroy_user_session_path, method: :delete%>
    <%= link_to "Start Chatting" , rooms_path %>
  <% else %>
    <%= link_to "Login",new_user_session_path %>
    <%= link_to "Sign Up", new_user_registration_path %>
  <%end%>

app/views/rooms/_room.html.erb
<div>
  <%= link_to room.name, room %>
</div>

app/views/rooms/index.html.erb
<div id="chatroom_container" class="row bg-dark text-light">
  <div id="side_panel" class="col-md-4 col-sm-4">
    <h5> <%= current_user.email %> </h5>
    <h4> Users </h4>
    <%= turbo_stream_from "users" %>
    <div id="users">
      <%= render @users %>
    </div>
    <h4> Rooms </h4>
    <%= turbo_stream_from "rooms" %>
    <%= render 'layouts/new_room_form' %>
    <div id="rooms">
      <%= render @rooms%>
    </div>
  </div>
  <div id="room_container"
  class="col-md-8 col-sm-8 bg-dark text-light">
    <% if @single_room %>
      <div id="single_room">
        <h4 class="text-center"> <%= @user&.email || @single_room.name %> </h4>
        <%= turbo_stream_from @single_room %>
        <div id="messages">
          <%= render @messages %>
        </div>
        <%= render 'layouts/new_message_form' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div>
  <%= link_to user.email, user %>
</div>